import { Camera, Coffee, Compass, Map, MapPin, Tent } from 'lucide-react';
import { GridItem } from './grid.types';

export const GRID_ITEMS: GridItem[] = [
  {
    id: 'culinary',
    type: 'feature',
    title: 'Culinary Secrets',
    subtitle: 'Taste street food with locals who know the hygiene-safe hidden gems.',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1000&auto=format&fit=crop',
    icon: Coffee,
    colSpan: 'md:col-span-2',
    rowSpan: 'md:row-span-2',
    href: '/tours/food',
    ctaText: 'Explore Food Tours',
  },
  {
    id: 'wild',
    type: 'feature',
    title: 'Wild & Free',
    subtitle: 'Off-grid hiking trails.',
    image: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?q=80&w=1000&auto=format&fit=crop',
    icon: Tent,
    colSpan: 'md:col-span-1',
    rowSpan: 'md:row-span-2',
    theme: 'light',
  },
  {
    id: 'cta-explore',
    type: 'cta',
    title: 'Not sure where to go?',
    icon: Compass,
    theme: 'slate',
    href: '/tours',
    ctaText: 'Explore Now',
  },
  {
    id: 'cta-gems',
    type: 'cta',
    title: 'Find hidden gems near you',
    icon: MapPin,
    theme: 'primary',
    href: '/tours',
    ctaText: 'Discover Now',
  },
  {
    id: 'insta',
    type: 'feature',
    title: 'Insta-Worthy Spots',
    subtitle: 'Photography', 
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?q=40&w=1000&auto=format&fit=crop',
    icon: Camera,
    colSpan: 'md:col-span-2',
    rowSpan: 'md:row-span-1',
  },
  {
    id: 'stat',
    type: 'stat',
    title: 'Cities Live',
    subtitle: '8+',
    icon: Map,
    colSpan: 'md:col-span-1',
    rowSpan: 'md:row-span-1',
  },
  {
    id: 'bus',
    type: 'image',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=1000&auto=format&fit=crop',
    colSpan: 'md:col-span-1',
    rowSpan: 'md:row-span-1',
  },
];