import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import LogoutSuccessToast from "@/components/shared/toast/LogoutSuccessToast";
import NavbarServer from "@/components/shared/home/NavbarServer";
import Footer from "@/components/shared/home/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <NavbarServer />
        <main className="grow my-20">
          {children}
        </main>
        <Footer />
        <Toaster position="top-right" richColors />
        <LogoutSuccessToast />
      </body>
    </html>
  );
}
