export const dynamic = "force-dynamic"; // <--- ADD THIS
import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import LogoutSuccessToast from "@/components/shared/toast/LogoutSuccessToast";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const notoSans = Noto_Sans({
  variable: "--noto-sans",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    template: "%s | GuideNest", // %s is replaced by the child page title
    default: "GuideNest - Authentic Travel Experiences", // Default if no child title
  },
  description: "Connect with passionate local guides for authentic, personalized travel experiences worldwide.",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "GuideNest - Authentic Travel Experiences",
    description: "Discover the world through local eyes. Book unique tours and experiences.",
    siteName: "GuideNest",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={` antialiased ${notoSans.className}`}
      >


        {children}


        <Toaster position="top-right" richColors />
        <Suspense fallback={null}>
          <LogoutSuccessToast />
        </Suspense>
      </body>
    </html>
  );
}
